---
# wifimon vagrant setup

- hosts:
    - pi-point
    - testpoint
  remote_user: vagrant
  become: true
  become_method: sudo
  become_user: root
  roles:
    - ansible-role-perfsonar-testpoint
    - ansible-role-rabbitmq



- hosts: elastic
  remote_user: vagrant
  become: true
  become_method: sudo
  become_user: root
  roles:
    - ansible-role-elastic
